version: 1
reporting: checks-v1
policy:
#   pullRequests: public_restricted
  pullRequests: public
tasks:
  - $if: 'tasks_for == "github-pull-request-untrusted"'
    then:
      taskQueueId: built-in/fail
      schedulerId: taskcluster-ui
      created: {$fromNow: ''}
      deadline: {$fromNow: '1 day'}
      payload: {}
      metadata:
        name: example-task-1
        description: An **example** task
        owner: ykurmyza@mozilla.com
        source: http://taskcluster/tasks/create
    else:
      taskQueueId: built-in/succeed
      schedulerId: taskcluster-ui
      created: {$fromNow: ''}
      deadline: {$fromNow: '1 day'}
      payload: {}
      metadata:
        name: example-task-1
        description: An **example** task
        owner: ykurmyza@mozilla.com
        source: http://taskcluster/tasks/create
