version: 1
reporting: checks-v1
policy:
#   pullRequests: public_restricted
  pullRequests: public
tasks:
  - $if: 'tasks_for == "github-pull-request-untrusted"'
    then:
      taskQueueId: built-in/fail
      schedulerId: taskcluster-ui
      created: {$fromNow: ''}
      deadline: {$fromNow: '1 day'}
      payload: {}
      metadata:
        name: example-task-1
        description: An **example** task
        owner: ykurmyza@mozilla.com
        source: http://taskcluster/tasks/create
    else:
      taskQueueId: docker-compose/generic-worker
      schedulerId: taskcluster-ui
      created: {$fromNow: ''}
      deadline: {$fromNow: '1 day'}
      payload:
        command:
           - - /bin/bash
             - '-c'
             - for ((i=1;i<=500;i++)); do echo $i; sleep 0.1; done
        maxRunTime: 630
      metadata:
        name: example-task-1
        description: An **example** task
        owner: ykurmyza@mozilla.com
        source: http://taskcluster/tasks/create
